name: Manual workflow for automated tests on app-staging, e2e-branch all

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: npm install
      - name: Test
        shell: bash
        run: npm run testLocal
      - name: Screenshot handling
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: wdio-error-screenshots
          path: errorShots
          retention-days: 10
