name: Manual workflow for automated tests on app-staging, e2e-branch all

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: npm install
      - name: Test
        shell: bash
        run: npm run testLocal
      - name: Screenshot handling
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: wdio-error-screenshots
          path: errorScreenshots
          retention-days: 10
      - name: rin docker image for allure-report
       
        run: docker build . -t allure-gen & docker run -v ${PWD}:/github/workspace allure-gen allure-results allure-report
      - name: Create Allure report
        uses: esemi/action-allure-report@v0.2.0
        if: always()      
        with:
          allure-results: allure-results
          keep_reports: 20
          

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
